name: Delete stdlibs in staging central

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Release tag (v220x.x.x) / Branch (master)
        required: true
        default: master

jobs:
  delete-from-staging-central:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get gradle.properties from the distribution
        uses: wei/wget@v1
        with:
          args: https://raw.githubusercontent.com/ballerina-platform/ballerina-distribution/${{github.event.inputs.tag}}/gradle.properties
             -P ./dependabot/resources
      - name: Create JSON file to store module details
        run: touch ModuleDetails.json
      - name: Execute Ballerina script
        uses: ballerina-platform/ballerina-action@2201.0.3
        with:
          args: run ./dependabot/delete_staging_central_stdlibs.bal
      - name: Store module details in a JSON
        id: store_module_details
        run: echo "::set-output name=module_details::`cat ModuleDetails.json`"
      - name: Trigger workflow to delete stdlibs
        run: |
          curl -X POST \
          -d '{"event_type": "trigger_delete_stdlibs_from_staging", "client_payload": ${{steps.store_module_details.outputs.module_details}}}' \
          -H 'Content-Type: application/json' \
          -H 'Authorization: token ${{secrets.BALLERINA_BOT_TOKEN}}' \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          'https://api.github.com/repos/wso2-enterprise/ballerina-registry/dispatches'
